const Vods = [
{id: 0,date: "4/24/2020",cid: 1,creator: "Dream",title: "Minecraft 1.16 survival",archiver: "CameronMan",archiveLink: "https://archive.org/details/twitcharchive.dreamwastaken.Minecraft_1_16_survival",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=lsYbGIyzVIE",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 1,date: "4/25/2020",cid: 2,creator: "GeorgeNotFound",title: "Minecraft Survival 1.16 Snapshot",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-survival-1.16-snapshot-partially-missing-georgenotfound-2020.04.24",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=BTCg08-v9Rk",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 2,date: "4/28/2020",cid: 2,creator: "GeorgeNotFound",title: "Minecraft Survival 1.16 Snapshot AGAIN",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-survival-1.16-snapshot-again-partially-missing-georgenotfound-2020.04.28",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=o6rapBiteH8",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 3,date: "4/29/2020",cid: 1,creator: "Dream",title: "Minecraft Manhunt Live",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-manhunt-live-partially-missing-dreamwastaken-2020.04.29",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=hbCAOS_c9b8",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 4,date: "5/2/2020",cid: 1,creator: "Dream",title: "Minecraft Speedruns",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-speedruns-dreamwastaken-2020.05.02",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=Ib6RXdMNROc",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 5,date: "5/2/2020",cid: 2,creator: "GeorgeNotFound",title: "woops",archiver: "Rogue123987",archiveLink: "https://archive.org/details/woops-georgenotfound-2020.05.02",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=fbHfdwd-_zo",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 6,date: "5/5/2020",cid: 2,creator: "GeorgeNotFound",title: "1.16 survival WOOO",archiver: "Rogue123987",archiveLink: "https://archive.org/details/1.16-survival-wooo-georgenotfound-2020.05.05",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=GGmu8bZ_GSc",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 7,date: "5/5/2020",cid: 4,creator: "Sapnap",title: "Dream Team Survival World",archiver: "",archiveLink: "",youtubeRestorer: "",youtubeLink: "",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 8,date: "5/5/2020",cid: 1,creator: "Dream",title: "Minecraft 1.16 chilling",archiver: "fouach",archiveLink: "https://archive.org/details/20200519-625550512-minecraft-speedruns-qm",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=UrZlCaJXcrI`https://www.youtube.com/watch?v=YK-NVmBch_w",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 9,date: "5/6/2020",cid: 2,creator: "GeorgeNotFound",title: "survival time :)",archiver: "Rogue123987",archiveLink: "https://archive.org/details/survival-time-georgenotfound-2020.05.06",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=4w4TF_91jiw",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 10,date: "5/7/2020",cid: 2,creator: "GeorgeNotFound",title: "Minecraft, But I Have No Friends...",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-but-i-have-no-friends-georgenotfound-2020.05.07",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=vVaP8gLzE4s",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 11,date: "5/7/2020",cid: 1,creator: "Dream",title: "Minecraft memes",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-memes-dreamwastaken-2020.05.07",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=8nlu8zWViUs",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 12,date: "5/7/2020",cid: 4,creator: "Sapnap",title: "Dream Team Survival World",archiver: "",archiveLink: "",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=z3SHj6jG4Ns",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 13,date: "5/8/2020",cid: 4,creator: "Sapnap",title: "Simpnap v4?",archiver: "",archiveLink: "",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=Ri1DEsqtlcw",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 14,date: "5/10/2020",cid: 2,creator: "GeorgeNotFound",title: "Random Minecraft Memes",archiver: "Rogue123987",archiveLink: "https://archive.org/details/random-minecraft-memes-georgenotfound-2020.05.10",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=K1F_t1DWwsk",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
{id: 15,date: "5/10/2020",cid: 1,creator: "Dream",title: "Minecraft speedruns 1.14",archiver: "Rogue123987",archiveLink: "https://archive.org/details/minecraft-speedruns-1.14-dreamwastaken-2020.05.10",youtubeRestorer: "",youtubeLink: "https://www.youtube.com/watch?v=xc75h2ShOhI",notesOne: "",notesOneLink: "",notesTwo: "",notesTwoLink: "",isAlt: false},
];
export default Vods;
